---
- hosts: 10.0.0.5
  become: yes
  tasks:
  - name: i want to execute direct Linux command
    command: hostname -f
    register: myfisttastsresult

  - name: i want to debug first tasks result
    debug:
       msg: "{{myfisttastsresult}}"

  - name: i want to install git 
    apt:
      name: git
      state: present
    when: myfisttastsresult.stderr== ""

  - name: i want to install tree
    apt: 
      name: tree
      state: present
    when: myfisttastsresult.stderr !=""
