---
- hosts: mywebservers
  become: yes
  gather_facts: yes
  tasks: 
  - name: in this tasks , i want to install apache2 webservers on ubutnu
    apt:
      name: "{{mywebpackonubuntu}}"
      state: present
    when: ansible_os_family== "Debian"
  - name: in this tasks, i want to start webservers on ubutnu
    service:
      name: "{{mywebpackonubuntu}}"
      state: started
    when: ansible_os_family== "Debian"
  - name: in this tasks, i want to install httpd webservers on RedHat
    dnf:
      name: "{{mywebpackonredhat}}"
      state: present
    when: ansible_os_family== "RedHat"
  - name: in this tasks, i want to start webservers on RedHat
    service:
       name: "{{mywebpackonredhat}}"
       state: started
    when: ansible_os_family== "RedHat"